### ISSUE TITLE
run `cronq-injector` cann't create table cronq.jobs

### ISSUE THREAD

**Issue by lj2007331** [seatgeek/cronq#27]
[root@10.4.55.40 ~]# /usr/local/python27/bin/cronq-injector
[2015-12-17 11:15:27] cronq.queue_connection - INFO - Hosts are: ['10.21.200.236']
[2015-12-17 11:15:27] cronq.queue_connection - INFO - Trying to connect to host: 10.21.200.236
Traceback (most recent call last):
  File "/usr/local/python27/bin/cronq-injector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python27/lib/python2.7/site-packages/cronq/injector.py", line 20, in main
    injector = Injector(Storage(Publisher()))
  File "/usr/local/python27/lib/python2.7/site-packages/cronq/injector.py", line 9, in __init__
    storage.bootstrap()
  File "/usr/local/python27/lib/python2.7/site-packages/cronq/backends/mysql.py", line 54, in bootstrap
    model.__table__.create(self._engine)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 655, in create
    checkfirst=checkfirst)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1617, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 732, in visit_table
    self.connection.execute(CreateTable(table))
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
    compiled
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/python27/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/cursor.py", line 494, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/connection.py", line 683, in cmd_query
    statement))
  File "/usr/local/python27/lib/python2.7/site-packages/mysql/connector/connection.py", line 601, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.DatabaseError: (DatabaseError) 1005 (HY000): Can't create table 'cronq.jobs' (errno: 150) '\nCREATE TABLE jobs (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\tname CHAR(255), \n\t`interval` DATETIME, \n\tnext_run DATETIME, \n\tlast_run_start DATETIME, \n\tlast_run_stop DATETIME, \n\tlast_run_status CHAR(32), \n\tcurrent_status CHAR(32), \n\trouting_key CHAR(32), \n\tcommand TEXT, \n\trun_now INTEGER, \n\tlocked_by CHAR(64), \n\tcategory_id INTEGER, \n\tPRIMARY KEY (id), \n\tUNIQUE (category_id, name), \n\tFOREIGN KEY(category_id) REFERENCES categories (id)\n)ENGINE=InnoDB\n\n' {}

**Comment by josegonzalez** [comment]
Does your user have `create table` permissions?

**Comment by lj2007331** [comment]
I find this problem, Create a table sequential jobs,Category, You can changed to:
https://github.com/seatgeek/cronq/blob/master/cronq/backends/mysql.py
    def bootstrap(self):
        models = [
            Category,
            Job,
            Event,
        ]

**Comment by josegonzalez** [comment]
PR welcome :)
